### ISSUE TITLE
Populate Message extras `url`

### ISSUE THREAD

**Issue by jayvdb** [zulip/errbot-backend-zulip#6]
The slack backend provides a `Message.extras['url']` , which is a link to the message

```
        msg.extras['url'] = 'https://{domain}.slack.com/archives/{channelid}/p{ts}'.format(
            domain=self.sc.server.domain,
            channelid=channel_link_name,
            ts=self._ts_for_message(msg).replace('.', '')
        )
```

I've created a patch for Gitter backend to do the same : https://github.com/errbotio/err-backend-gitter/pull/32

And ideally Zulip does as well.
It is reasonably easy to create the URL for a topic of a stream, but I suspect that the `/near/id` part is not available in the API.  At least I couldnt find it quickly.

**Comment by timabbott** [comment]
@jayvdb you need the message ID (which should be available in the message object from the Zulip API) and then you can construct a URL with a `/#narrow/stream/foo/topic/bar/near/ID` structure (the operator/operand pairs can be in any order)
